name: Update Matches Every 5 Minutes

on:
  schedule:
    # هذا الكود يعني التشغيل كل 5 دقائق
    - cron: '*/59 * * * *'
  workflow_dispatch: # يتيح لك تشغيل السكربت يدوياً للتجربة

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: Run Scraper
        env:
          FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
          TZ: 'Asia/Aden' # تحديد المنطقة الزمنية هنا أيضاً
        run: python sam.py
